on: [push, pull_request]

name: CI

jobs:

  build-test-android:
    name: Build and test android targets
    runs-on: macos-10.15
    strategy:
      matrix:
        include:
          - target: x86_64-linux-android
            test: true
            api: 28
            arch: x86_64
          - target: i686-linux-android
            test: true
            api: 28
            arch: x86
          - target: aarch64-linux-android
          - target: armv7-linux-androideabi
    env:
      BUILD_TARGETS: ${{ matrix.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set default toolchain
        run: rustup default stable
      - name: Set profile
        run: rustup set profile minimal
      - name: Add target
        run: rustup target add ${{ matrix.target }}
      - name: Build
        run: ./gradlew :android:build
      - name: Android emulator test
        if: ${{ matrix.test == true }}
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api }}
          arch: ${{ matrix.arch }}
          script: ./gradlew :android:connectedDebugAndroidTest

  build-all-android:
    name: Build all android targets
    runs-on: ubuntu-18.04
    env:
      BUILD_TARGETS: aarch64,armv7,x86_64,i686
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set default toolchain
        run: rustup default stable
      - name: Set profile
        run: rustup set profile minimal
      - name: Add targets
        run: rustup target add x86_64-linux-android i686-linux-android aarch64-linux-android armv7-linux-androideabi
      - name: Build
        run: ./gradlew :android:build

  rust-fmt:
    name: Rust fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set default toolchain
        run: rustup default ${{ matrix.rust }}
      - name: Set profile
        run: rustup set profile minimal
      - name: Add rustfmt
        run: rustup component add rustfmt
      - name: Check fmt
        run: cargo fmt --all -- --check